# Generated by Django 5.2.9 on 2025-12-19 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Foreign key referencing the user who created the record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Foreign key referencing the user who deleted the record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='restored_by',
            field=models.ForeignKey(blank=True, help_text='Foreign key referencing the user who restored the record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_restored_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prices', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Foreign key referencing the user who updated the record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['stock', 'timestamp'], name='pricing_sto_stock_i_336490_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockprice',
            constraint=models.UniqueConstraint(fields=('stock', 'timestamp', 'source'), name='unique_stock_price_per_source'),
        ),
    ]
